/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for Department controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { RequestOptions, CreateDepartmentDTO } from "../models";

@Injectable({ providedIn: "root" })
export class DepartmentService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    apiDepartmentDashboardGet(observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    apiDepartmentDashboardGet(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    apiDepartmentDashboardGet(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    apiDepartmentDashboardGet(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/Department/dashboard`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    apiDepartmentDepartmentlistGet(observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    apiDepartmentDepartmentlistGet(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    apiDepartmentDepartmentlistGet(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    apiDepartmentDepartmentlistGet(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/Department/Departmentlist`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    apiDepartmentDistributionGet(observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    apiDepartmentDistributionGet(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    apiDepartmentDistributionGet(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    apiDepartmentDistributionGet(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/Department/distribution`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    apiDepartmentCreateWithIdPost(createDepartmentDTO?: CreateDepartmentDTO, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    apiDepartmentCreateWithIdPost(createDepartmentDTO?: CreateDepartmentDTO, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    apiDepartmentCreateWithIdPost(createDepartmentDTO?: CreateDepartmentDTO, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    apiDepartmentCreateWithIdPost(createDepartmentDTO?: CreateDepartmentDTO, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/Department/create-with-id`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, createDepartmentDTO, requestOptions);
    }

    apiDepartmentGet(observe?: 'body', options?: RequestOptions<'json'>): Observable<Array<CreateDepartmentDTO>>;
    apiDepartmentGet(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Array<CreateDepartmentDTO>>>;
    apiDepartmentGet(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Array<CreateDepartmentDTO>>>;
    apiDepartmentGet(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/Department`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    apiDepartmentPost(createDepartmentDTO?: CreateDepartmentDTO, observe?: 'body', options?: RequestOptions<'json'>): Observable<CreateDepartmentDTO>;
    apiDepartmentPost(createDepartmentDTO?: CreateDepartmentDTO, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<CreateDepartmentDTO>>;
    apiDepartmentPost(createDepartmentDTO?: CreateDepartmentDTO, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<CreateDepartmentDTO>>;
    apiDepartmentPost(createDepartmentDTO?: CreateDepartmentDTO, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/Department`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, createDepartmentDTO, requestOptions);
    }

    apiDepartmentIdGet(id: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<CreateDepartmentDTO>;
    apiDepartmentIdGet(id: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<CreateDepartmentDTO>>;
    apiDepartmentIdGet(id: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<CreateDepartmentDTO>>;
    apiDepartmentIdGet(id: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/Department/${id}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    apiDepartmentIdPut(id: string, createDepartmentDTO?: CreateDepartmentDTO, observe?: 'body', options?: RequestOptions<'json'>): Observable<CreateDepartmentDTO>;
    apiDepartmentIdPut(id: string, createDepartmentDTO?: CreateDepartmentDTO, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<CreateDepartmentDTO>>;
    apiDepartmentIdPut(id: string, createDepartmentDTO?: CreateDepartmentDTO, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<CreateDepartmentDTO>>;
    apiDepartmentIdPut(id: string, createDepartmentDTO?: CreateDepartmentDTO, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/Department/${id}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.put(url, createDepartmentDTO, requestOptions);
    }

    apiDepartmentIdDelete(id: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    apiDepartmentIdDelete(id: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    apiDepartmentIdDelete(id: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    apiDepartmentIdDelete(id: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/Department/${id}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.delete(url, requestOptions);
    }
}
