/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated service exports
* Do not edit this file manually
*/
export { DepartmentService } from "./department.service";
export { DesignationService } from "./designation.service";
export { EmployeeService } from "./employee.service";
export { LevelsService } from "./levels.service";
export { OnboardingService } from "./onboarding.service";
export { RolesService } from "./roles.service";
