/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for Levels controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { RequestOptions, LevelsDto } from "../models";

@Injectable({ providedIn: "root" })
export class LevelsService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    apiLevelsGetAllLevelsGet(observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    apiLevelsGetAllLevelsGet(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    apiLevelsGetAllLevelsGet(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    apiLevelsGetAllLevelsGet(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/Levels/GetAllLevels`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    apiLevelsCreatelevelsPost(levelsDto?: LevelsDto, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    apiLevelsCreatelevelsPost(levelsDto?: LevelsDto, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    apiLevelsCreatelevelsPost(levelsDto?: LevelsDto, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    apiLevelsCreatelevelsPost(levelsDto?: LevelsDto, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/Levels/Createlevels`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, levelsDto, requestOptions);
    }

    apiLevelsGet(observe?: 'body', options?: RequestOptions<'json'>): Observable<Array<LevelsDto>>;
    apiLevelsGet(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Array<LevelsDto>>>;
    apiLevelsGet(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Array<LevelsDto>>>;
    apiLevelsGet(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/Levels`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    apiLevelsPost(levelsDto?: LevelsDto, observe?: 'body', options?: RequestOptions<'json'>): Observable<LevelsDto>;
    apiLevelsPost(levelsDto?: LevelsDto, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<LevelsDto>>;
    apiLevelsPost(levelsDto?: LevelsDto, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<LevelsDto>>;
    apiLevelsPost(levelsDto?: LevelsDto, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/Levels`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, levelsDto, requestOptions);
    }

    apiLevelsIdGet(id: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<LevelsDto>;
    apiLevelsIdGet(id: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<LevelsDto>>;
    apiLevelsIdGet(id: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<LevelsDto>>;
    apiLevelsIdGet(id: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/Levels/${id}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    apiLevelsIdPut(id: string, levelsDto?: LevelsDto, observe?: 'body', options?: RequestOptions<'json'>): Observable<LevelsDto>;
    apiLevelsIdPut(id: string, levelsDto?: LevelsDto, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<LevelsDto>>;
    apiLevelsIdPut(id: string, levelsDto?: LevelsDto, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<LevelsDto>>;
    apiLevelsIdPut(id: string, levelsDto?: LevelsDto, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/Levels/${id}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.put(url, levelsDto, requestOptions);
    }

    apiLevelsIdDelete(id: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    apiLevelsIdDelete(id: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    apiLevelsIdDelete(id: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    apiLevelsIdDelete(id: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/Levels/${id}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.delete(url, requestOptions);
    }
}
