/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for Onboarding controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { EmployeePersonalDetailsDto, RequestOptions, ReviewDto, EmployeeIdentityInfoDto, EmployeeAddressDto, EmployeeEducationDto, EmployeeExperienceDto, EmployeeBankDetailDto, EmployeeEmergencyContactDto } from "../models";

@Injectable({ providedIn: "root" })
export class OnboardingService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    apiOnboardingEmployeeIdPersonalDetailsPost(employeeId: string, employeePersonalDetailsDto?: EmployeePersonalDetailsDto, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    apiOnboardingEmployeeIdPersonalDetailsPost(employeeId: string, employeePersonalDetailsDto?: EmployeePersonalDetailsDto, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    apiOnboardingEmployeeIdPersonalDetailsPost(employeeId: string, employeePersonalDetailsDto?: EmployeePersonalDetailsDto, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    apiOnboardingEmployeeIdPersonalDetailsPost(employeeId: string, employeePersonalDetailsDto?: EmployeePersonalDetailsDto, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/Onboarding/${employeeId}/personal-details`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, employeePersonalDetailsDto, requestOptions);
    }

    apiOnboardingEmployeeIdPersonalDetailsReviewPut(employeeId: string, reviewDto?: ReviewDto, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    apiOnboardingEmployeeIdPersonalDetailsReviewPut(employeeId: string, reviewDto?: ReviewDto, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    apiOnboardingEmployeeIdPersonalDetailsReviewPut(employeeId: string, reviewDto?: ReviewDto, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    apiOnboardingEmployeeIdPersonalDetailsReviewPut(employeeId: string, reviewDto?: ReviewDto, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/Onboarding/${employeeId}/personal-details/review`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.put(url, reviewDto, requestOptions);
    }

    apiOnboardingEmployeeIdIdentityInfoPost(employeeId: string, employeeIdentityInfoDto?: EmployeeIdentityInfoDto, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    apiOnboardingEmployeeIdIdentityInfoPost(employeeId: string, employeeIdentityInfoDto?: EmployeeIdentityInfoDto, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    apiOnboardingEmployeeIdIdentityInfoPost(employeeId: string, employeeIdentityInfoDto?: EmployeeIdentityInfoDto, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    apiOnboardingEmployeeIdIdentityInfoPost(employeeId: string, employeeIdentityInfoDto?: EmployeeIdentityInfoDto, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/Onboarding/${employeeId}/identity-info`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, employeeIdentityInfoDto, requestOptions);
    }

    apiOnboardingEmployeeIdAddressPost(employeeId: string, employeeAddressDto?: EmployeeAddressDto, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    apiOnboardingEmployeeIdAddressPost(employeeId: string, employeeAddressDto?: EmployeeAddressDto, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    apiOnboardingEmployeeIdAddressPost(employeeId: string, employeeAddressDto?: EmployeeAddressDto, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    apiOnboardingEmployeeIdAddressPost(employeeId: string, employeeAddressDto?: EmployeeAddressDto, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/Onboarding/${employeeId}/address`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, employeeAddressDto, requestOptions);
    }

    apiOnboardingEmployeeIdAddressReviewPut(employeeId: string, reviewDto?: ReviewDto, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    apiOnboardingEmployeeIdAddressReviewPut(employeeId: string, reviewDto?: ReviewDto, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    apiOnboardingEmployeeIdAddressReviewPut(employeeId: string, reviewDto?: ReviewDto, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    apiOnboardingEmployeeIdAddressReviewPut(employeeId: string, reviewDto?: ReviewDto, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/Onboarding/${employeeId}/address/review`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.put(url, reviewDto, requestOptions);
    }

    apiOnboardingEmployeeIdEducationPost(employeeId: string, employeeEducationDto?: EmployeeEducationDto, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    apiOnboardingEmployeeIdEducationPost(employeeId: string, employeeEducationDto?: EmployeeEducationDto, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    apiOnboardingEmployeeIdEducationPost(employeeId: string, employeeEducationDto?: EmployeeEducationDto, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    apiOnboardingEmployeeIdEducationPost(employeeId: string, employeeEducationDto?: EmployeeEducationDto, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/Onboarding/${employeeId}/education`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, employeeEducationDto, requestOptions);
    }

    apiOnboardingEducationEducationIdReviewPut(educationId: string, reviewDto?: ReviewDto, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    apiOnboardingEducationEducationIdReviewPut(educationId: string, reviewDto?: ReviewDto, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    apiOnboardingEducationEducationIdReviewPut(educationId: string, reviewDto?: ReviewDto, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    apiOnboardingEducationEducationIdReviewPut(educationId: string, reviewDto?: ReviewDto, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/Onboarding/education/${educationId}/review`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.put(url, reviewDto, requestOptions);
    }

    apiOnboardingEmployeeIdExperiencePost(employeeId: string, employeeExperienceDto?: EmployeeExperienceDto, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    apiOnboardingEmployeeIdExperiencePost(employeeId: string, employeeExperienceDto?: EmployeeExperienceDto, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    apiOnboardingEmployeeIdExperiencePost(employeeId: string, employeeExperienceDto?: EmployeeExperienceDto, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    apiOnboardingEmployeeIdExperiencePost(employeeId: string, employeeExperienceDto?: EmployeeExperienceDto, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/Onboarding/${employeeId}/experience`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, employeeExperienceDto, requestOptions);
    }

    apiOnboardingEmployeeIdUploadDocumentPost(employeeId: string, DocumentType: string, File: Blob, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    apiOnboardingEmployeeIdUploadDocumentPost(employeeId: string, DocumentType: string, File: Blob, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    apiOnboardingEmployeeIdUploadDocumentPost(employeeId: string, DocumentType: string, File: Blob, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    apiOnboardingEmployeeIdUploadDocumentPost(employeeId: string, DocumentType: string, File: Blob, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/Onboarding/${employeeId}/upload-document`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Remove Content-Type for multipart (browser will set it with boundary)
        headers = headers.delete('Content-Type');

        const formData = new FormData();
        if (DocumentType !== undefined) {
            formData.append('DocumentType', String(DocumentType));
        }
        if (File !== undefined) {
            formData.append('File', File);
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, formData, requestOptions);
    }

    apiOnboardingEducationEducationIdDocumentPost(educationId: string, DocumentType: string, File: Blob, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    apiOnboardingEducationEducationIdDocumentPost(educationId: string, DocumentType: string, File: Blob, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    apiOnboardingEducationEducationIdDocumentPost(educationId: string, DocumentType: string, File: Blob, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    apiOnboardingEducationEducationIdDocumentPost(educationId: string, DocumentType: string, File: Blob, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/Onboarding/education/${educationId}/document`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Remove Content-Type for multipart (browser will set it with boundary)
        headers = headers.delete('Content-Type');

        const formData = new FormData();
        if (DocumentType !== undefined) {
            formData.append('DocumentType', String(DocumentType));
        }
        if (File !== undefined) {
            formData.append('File', File);
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, formData, requestOptions);
    }

    apiOnboardingExperienceExperienceIdDocumentPost(experienceId: string, DocumentType: string, File: Blob, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    apiOnboardingExperienceExperienceIdDocumentPost(experienceId: string, DocumentType: string, File: Blob, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    apiOnboardingExperienceExperienceIdDocumentPost(experienceId: string, DocumentType: string, File: Blob, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    apiOnboardingExperienceExperienceIdDocumentPost(experienceId: string, DocumentType: string, File: Blob, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/Onboarding/experience/${experienceId}/document`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Remove Content-Type for multipart (browser will set it with boundary)
        headers = headers.delete('Content-Type');

        const formData = new FormData();
        if (DocumentType !== undefined) {
            formData.append('DocumentType', String(DocumentType));
        }
        if (File !== undefined) {
            formData.append('File', File);
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, formData, requestOptions);
    }

    apiOnboardingEmployeeIdGovernmentIdentityPost(employeeId: string, DocumentType: string, File: Blob, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    apiOnboardingEmployeeIdGovernmentIdentityPost(employeeId: string, DocumentType: string, File: Blob, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    apiOnboardingEmployeeIdGovernmentIdentityPost(employeeId: string, DocumentType: string, File: Blob, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    apiOnboardingEmployeeIdGovernmentIdentityPost(employeeId: string, DocumentType: string, File: Blob, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/Onboarding/${employeeId}/government-identity`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Remove Content-Type for multipart (browser will set it with boundary)
        headers = headers.delete('Content-Type');

        const formData = new FormData();
        if (DocumentType !== undefined) {
            formData.append('DocumentType', String(DocumentType));
        }
        if (File !== undefined) {
            formData.append('File', File);
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, formData, requestOptions);
    }

    apiOnboardingEmployeeIdDocumentsGet(employeeId: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    apiOnboardingEmployeeIdDocumentsGet(employeeId: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    apiOnboardingEmployeeIdDocumentsGet(employeeId: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    apiOnboardingEmployeeIdDocumentsGet(employeeId: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/Onboarding/${employeeId}/documents`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    apiOnboardingExperienceExperienceIdReviewPut(experienceId: string, reviewDto?: ReviewDto, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    apiOnboardingExperienceExperienceIdReviewPut(experienceId: string, reviewDto?: ReviewDto, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    apiOnboardingExperienceExperienceIdReviewPut(experienceId: string, reviewDto?: ReviewDto, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    apiOnboardingExperienceExperienceIdReviewPut(experienceId: string, reviewDto?: ReviewDto, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/Onboarding/experience/${experienceId}/review`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.put(url, reviewDto, requestOptions);
    }

    apiOnboardingEmployeeIdBankDetailPost(employeeId: string, employeeBankDetailDto?: EmployeeBankDetailDto, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    apiOnboardingEmployeeIdBankDetailPost(employeeId: string, employeeBankDetailDto?: EmployeeBankDetailDto, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    apiOnboardingEmployeeIdBankDetailPost(employeeId: string, employeeBankDetailDto?: EmployeeBankDetailDto, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    apiOnboardingEmployeeIdBankDetailPost(employeeId: string, employeeBankDetailDto?: EmployeeBankDetailDto, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/Onboarding/${employeeId}/bank-detail`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, employeeBankDetailDto, requestOptions);
    }

    apiOnboardingBankDetailBankDetailIdReviewPut(bankDetailId: string, reviewDto?: ReviewDto, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    apiOnboardingBankDetailBankDetailIdReviewPut(bankDetailId: string, reviewDto?: ReviewDto, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    apiOnboardingBankDetailBankDetailIdReviewPut(bankDetailId: string, reviewDto?: ReviewDto, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    apiOnboardingBankDetailBankDetailIdReviewPut(bankDetailId: string, reviewDto?: ReviewDto, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/Onboarding/bank-detail/${bankDetailId}/review`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.put(url, reviewDto, requestOptions);
    }

    apiOnboardingEmployeeIdEmergencyContactPost(employeeId: string, employeeEmergencyContactDto?: EmployeeEmergencyContactDto, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    apiOnboardingEmployeeIdEmergencyContactPost(employeeId: string, employeeEmergencyContactDto?: EmployeeEmergencyContactDto, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    apiOnboardingEmployeeIdEmergencyContactPost(employeeId: string, employeeEmergencyContactDto?: EmployeeEmergencyContactDto, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    apiOnboardingEmployeeIdEmergencyContactPost(employeeId: string, employeeEmergencyContactDto?: EmployeeEmergencyContactDto, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/Onboarding/${employeeId}/emergency-contact`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, employeeEmergencyContactDto, requestOptions);
    }

    apiOnboardingEmergencyContactContactIdReviewPut(contactId: string, reviewDto?: ReviewDto, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    apiOnboardingEmergencyContactContactIdReviewPut(contactId: string, reviewDto?: ReviewDto, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    apiOnboardingEmergencyContactContactIdReviewPut(contactId: string, reviewDto?: ReviewDto, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    apiOnboardingEmergencyContactContactIdReviewPut(contactId: string, reviewDto?: ReviewDto, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/Onboarding/emergency-contact/${contactId}/review`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.put(url, reviewDto, requestOptions);
    }

    apiOnboardingEmployeesGet(pageNumber?: number, pageSize?: number, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    apiOnboardingEmployeesGet(pageNumber?: number, pageSize?: number, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    apiOnboardingEmployeesGet(pageNumber?: number, pageSize?: number, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    apiOnboardingEmployeesGet(pageNumber?: number, pageSize?: number, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/Onboarding/employees`;

        let params = new HttpParams();
        if (pageNumber != null) {
            params = HttpParamsBuilder.addToHttpParams(params, pageNumber, 'pageNumber');
        }
        if (pageSize != null) {
            params = HttpParamsBuilder.addToHttpParams(params, pageSize, 'pageSize');
        }

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            params,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    apiOnboardingDashboardSummaryGet(observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    apiOnboardingDashboardSummaryGet(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    apiOnboardingDashboardSummaryGet(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    apiOnboardingDashboardSummaryGet(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/Onboarding/dashboard-summary`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    apiOnboardingStatusDistributionGet(observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    apiOnboardingStatusDistributionGet(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    apiOnboardingStatusDistributionGet(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    apiOnboardingStatusDistributionGet(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/Onboarding/status-distribution`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }
}
