/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for Roles controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { RequestOptions, CreateRoleDto } from "../models";

@Injectable({ providedIn: "root" })
export class RolesService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    apiRolesDashboardGet(observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    apiRolesDashboardGet(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    apiRolesDashboardGet(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    apiRolesDashboardGet(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/Roles/dashboard`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    apiRolesRolesListGet(observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    apiRolesRolesListGet(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    apiRolesRolesListGet(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    apiRolesRolesListGet(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/Roles/RolesList`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    apiRolesGet(observe?: 'body', options?: RequestOptions<'json'>): Observable<Array<CreateRoleDto>>;
    apiRolesGet(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Array<CreateRoleDto>>>;
    apiRolesGet(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Array<CreateRoleDto>>>;
    apiRolesGet(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/Roles`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    apiRolesPost(createRoleDto?: CreateRoleDto, observe?: 'body', options?: RequestOptions<'json'>): Observable<CreateRoleDto>;
    apiRolesPost(createRoleDto?: CreateRoleDto, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<CreateRoleDto>>;
    apiRolesPost(createRoleDto?: CreateRoleDto, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<CreateRoleDto>>;
    apiRolesPost(createRoleDto?: CreateRoleDto, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/Roles`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, createRoleDto, requestOptions);
    }

    apiRolesIdGet(id: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<CreateRoleDto>;
    apiRolesIdGet(id: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<CreateRoleDto>>;
    apiRolesIdGet(id: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<CreateRoleDto>>;
    apiRolesIdGet(id: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/Roles/${id}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    apiRolesIdPut(id: string, createRoleDto?: CreateRoleDto, observe?: 'body', options?: RequestOptions<'json'>): Observable<CreateRoleDto>;
    apiRolesIdPut(id: string, createRoleDto?: CreateRoleDto, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<CreateRoleDto>>;
    apiRolesIdPut(id: string, createRoleDto?: CreateRoleDto, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<CreateRoleDto>>;
    apiRolesIdPut(id: string, createRoleDto?: CreateRoleDto, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/Roles/${id}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.put(url, createRoleDto, requestOptions);
    }

    apiRolesIdDelete(id: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    apiRolesIdDelete(id: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    apiRolesIdDelete(id: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    apiRolesIdDelete(id: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/Roles/${id}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.delete(url, requestOptions);
    }
}
