/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{html,ts}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        background: 'var(--background)',
        foreground: 'var(--foreground)',
        card: {
          DEFAULT: 'var(--card)',
          foreground: 'var(--card-foreground)',
        },
        popover: {
          DEFAULT: 'var(--popover)',
          foreground: 'var(--popover-foreground)',
        },
        primary: {
          DEFAULT: 'var(--primary)',
          foreground: 'var(--primary-foreground)',
          50: 'var(--hrms-primary-light)',
          100: '#c6d9fc',
          200: '#a0c0fa',
          300: '#7aa7f7',
          400: '#5d94f5',
          500: '#3f81f3',
          600: 'var(--hrms-primary)',
          700: '#316eef',
          800: '#2964ed',
          900: '#1b51ea',
        },
        secondary: {
          DEFAULT: 'var(--secondary)',
          foreground: 'var(--secondary-foreground)',
        },
        muted: {
          DEFAULT: 'var(--muted)',
          foreground: 'var(--muted-foreground)',
        },
        accent: {
          DEFAULT: 'var(--accent)',
          foreground: 'var(--accent-foreground)',
        },
        destructive: 'var(--destructive)',
        border: 'var(--border)',
        input: 'var(--input)',
        ring: 'var(--ring)',
        'chart-1': 'var(--chart-1)',
        'chart-2': 'var(--chart-2)',
        'chart-3': 'var(--chart-3)',
        'chart-4': 'var(--chart-4)',
        'chart-5': 'var(--chart-5)',
        'aurora-1': 'var(--aurora-1)',
        'aurora-2': 'var(--aurora-2)',
        'aurora-3': 'var(--aurora-3)',
        'hrms-bg': 'var(--hrms-bg)',
        'hrms-surface': 'var(--hrms-surface)',
        'hrms-text': 'var(--hrms-text)',
        'hrms-text-muted': 'var(--hrms-text-muted)',
        'hrms-border': 'var(--hrms-border)',
        'hrms-success': 'var(--hrms-success)',
        'hrms-warning': 'var(--hrms-warning)',
        'hrms-danger': 'var(--hrms-danger)',
        'hrms-info': 'var(--hrms-info)',
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) * 0.8)',
        sm: 'calc(var(--radius) * 0.6)',
      },
      fontFamily: {
        sans: ['Inter', 'Segoe UI', 'system-ui', 'sans-serif'],
      },
      boxShadow: {
        'hrms-sm': 'var(--hrms-shadow-sm)',
        'hrms': 'var(--hrms-shadow)',
        'hrms-lg': 'var(--hrms-shadow-lg)',
        'hrms-primary': 'var(--hrms-shadow-primary)',
      },
    },
  },
  plugins: [],
};
