/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { HttpContext, HttpHeaders } from "@angular/common/http";
export interface AddEmployeeDto {
    firstName: string | null;
    lastName: string | null;
    email: string | null;
    mobileNumber: string | null;
    dateOfBirth?: Date;
    departmentId?: string;
    joiningDate?: Date;
}

export interface CreateDepartmentDTO {
    name?: string | null;
    status?: Status;
    description?: string | null;
}

export interface CreateDesignationDto {
    title?: string | null;
    departmentId?: string;
    levelId?: string;
    status?: Status;
    description?: string | null;
}

export interface CreateRoleDto {
    name?: string | null;
    description?: string | null;
    status?: Status;
}

export interface EmployeeAddressDto {
    id?: string;
    employeeId?: string;
    addressLine1?: string | null;
    addressLine2?: string | null;
    city?: string | null;
    state?: string | null;
    country?: string | null;
    postalCode?: string | null;
}

export interface EmployeeBankDetailDto {
    bankName?: string | null;
    accountNumber?: string | null;
    ifscCode?: string | null;
    accountHolderName?: string | null;
    branchName?: string | null;
    accountType?: string | null;
    isPrimary?: boolean;
    isActive?: boolean;
    upiId?: string | null;
    cancelledChequePath?: string | null;
}

export interface EmployeeEducationDto {
    institutionName?: string | null;
    degree?: string | null;
    fieldOfStudy?: string | null;
    universityOrBoard?: string | null;
    specialization?: string | null;
    percentageOrCGPA?: number;
    startYear?: number;
    endYear?: number;
    grade?: string | null;
    qualificationLevel?: string | null;
}

export interface EmployeeEmergencyContactDto {
    name?: string | null;
    relationship?: string | null;
    alternateNumber?: string | null;
    address?: string | null;
    email?: string | null;
    phoneNumber?: string | null;
}

export interface EmployeeExperienceDto {
    companyName?: string | null;
    designation?: string | null;
    startDate?: Date;
    endDate?: Date | null;
    responsibilities?: string | null;
    employmentType?: EmploymentType;
    technologiesUsed?: Array<string>;
    currentCTC?: number;
    lastDrawnSalary?: number;
}

export interface EmployeeIdentityInfoDto {
    id?: string;
    employeeId?: string;
    aadhaarNumber?: string | null;
    panNumber?: string | null;
    passportNumber?: string | null;
    drivingLicenseNumber?: string | null;
    voterId?: string | null;
    aadhaarDocumentPath?: string | null;
    panDocumentPath?: string | null;
    passportDocumentPath?: string | null;
    drivingLicenseDocumentPath?: string | null;
    voterIdDocumentPath?: string | null;
}

export interface EmployeePersonalDetailsDto {
    middleName?: string | null;
    lastName?: string | null;
    placeOfBirth?: string | null;
    gender?: Gender;
    maritalStatus?: MaritalStatus;
    nationality?: string | null;
}

export enum EmploymentType {
    _1 = 1,
    _2 = 2,
    _3 = 3,
    _4 = 4,
    _5 = 5,
    _6 = 6,
    _7 = 7
}

export enum Gender {
    _1 = 1,
    _2 = 2,
    _3 = 3
}

export interface LevelsDto {
    name: string | null;
    levelOrder: number;
    description?: string | null;
}

export enum MaritalStatus {
    _1 = 1,
    _2 = 2,
    _3 = 3,
    _4 = 4
}

export enum OnboardingStatus {
    _1 = 1,
    _2 = 2,
    _3 = 3,
    _4 = 4,
    _5 = 5
}

export interface ReviewDto {
    status?: OnboardingStatus;
    hrComment?: string | null;
}

export enum Status {
    _1 = 1,
    _2 = 2
}

/** Request Options for Angular HttpClient requests */
export interface RequestOptions<TResponseType extends 'arraybuffer' | 'blob' | 'json' | 'text'> {
    headers?: HttpHeaders;
    reportProgress?: boolean;
    responseType?: TResponseType;
    withCredentials?: boolean;
    context?: HttpContext;
}
