/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for Payment controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { RequestOptions, PaymentDto } from "../models";

@Injectable({ providedIn: "root" })
export class PaymentService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    apiPaymentGet(observe?: 'body', options?: RequestOptions<'json'>): Observable<Array<PaymentDto>>;
    apiPaymentGet(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Array<PaymentDto>>>;
    apiPaymentGet(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Array<PaymentDto>>>;
    apiPaymentGet(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/Payment`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    apiPaymentPost(paymentDto?: PaymentDto, observe?: 'body', options?: RequestOptions<'json'>): Observable<PaymentDto>;
    apiPaymentPost(paymentDto?: PaymentDto, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<PaymentDto>>;
    apiPaymentPost(paymentDto?: PaymentDto, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<PaymentDto>>;
    apiPaymentPost(paymentDto?: PaymentDto, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/Payment`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, paymentDto, requestOptions);
    }

    apiPaymentIdGet(id: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<PaymentDto>;
    apiPaymentIdGet(id: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<PaymentDto>>;
    apiPaymentIdGet(id: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<PaymentDto>>;
    apiPaymentIdGet(id: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/Payment/${id}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    apiPaymentIdPut(id: string, paymentDto?: PaymentDto, observe?: 'body', options?: RequestOptions<'json'>): Observable<PaymentDto>;
    apiPaymentIdPut(id: string, paymentDto?: PaymentDto, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<PaymentDto>>;
    apiPaymentIdPut(id: string, paymentDto?: PaymentDto, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<PaymentDto>>;
    apiPaymentIdPut(id: string, paymentDto?: PaymentDto, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/Payment/${id}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.put(url, paymentDto, requestOptions);
    }
}
