/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for Plan controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { RequestOptions, PlanDto } from "../models";

@Injectable({ providedIn: "root" })
export class PlanService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    apiPlanGet(observe?: 'body', options?: RequestOptions<'json'>): Observable<Array<PlanDto>>;
    apiPlanGet(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Array<PlanDto>>>;
    apiPlanGet(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Array<PlanDto>>>;
    apiPlanGet(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/Plan`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    apiPlanPost(planDto?: PlanDto, observe?: 'body', options?: RequestOptions<'json'>): Observable<PlanDto>;
    apiPlanPost(planDto?: PlanDto, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<PlanDto>>;
    apiPlanPost(planDto?: PlanDto, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<PlanDto>>;
    apiPlanPost(planDto?: PlanDto, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/Plan`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, planDto, requestOptions);
    }

    apiPlanIdGet(id: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<PlanDto>;
    apiPlanIdGet(id: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<PlanDto>>;
    apiPlanIdGet(id: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<PlanDto>>;
    apiPlanIdGet(id: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/Plan/${id}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    apiPlanIdPut(id: string, planDto?: PlanDto, observe?: 'body', options?: RequestOptions<'json'>): Observable<PlanDto>;
    apiPlanIdPut(id: string, planDto?: PlanDto, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<PlanDto>>;
    apiPlanIdPut(id: string, planDto?: PlanDto, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<PlanDto>>;
    apiPlanIdPut(id: string, planDto?: PlanDto, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/Plan/${id}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.put(url, planDto, requestOptions);
    }
}
