/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for Subscription controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { RequestOptions, SubscriptionDto } from "../models";

@Injectable({ providedIn: "root" })
export class SubscriptionService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    apiSubscriptionGet(observe?: 'body', options?: RequestOptions<'json'>): Observable<Array<SubscriptionDto>>;
    apiSubscriptionGet(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Array<SubscriptionDto>>>;
    apiSubscriptionGet(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Array<SubscriptionDto>>>;
    apiSubscriptionGet(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/Subscription`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    apiSubscriptionPost(subscriptionDto?: SubscriptionDto, observe?: 'body', options?: RequestOptions<'json'>): Observable<SubscriptionDto>;
    apiSubscriptionPost(subscriptionDto?: SubscriptionDto, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<SubscriptionDto>>;
    apiSubscriptionPost(subscriptionDto?: SubscriptionDto, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<SubscriptionDto>>;
    apiSubscriptionPost(subscriptionDto?: SubscriptionDto, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/Subscription`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, subscriptionDto, requestOptions);
    }

    apiSubscriptionIdGet(id: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<SubscriptionDto>;
    apiSubscriptionIdGet(id: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<SubscriptionDto>>;
    apiSubscriptionIdGet(id: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<SubscriptionDto>>;
    apiSubscriptionIdGet(id: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/Subscription/${id}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    apiSubscriptionIdPut(id: string, subscriptionDto?: SubscriptionDto, observe?: 'body', options?: RequestOptions<'json'>): Observable<SubscriptionDto>;
    apiSubscriptionIdPut(id: string, subscriptionDto?: SubscriptionDto, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<SubscriptionDto>>;
    apiSubscriptionIdPut(id: string, subscriptionDto?: SubscriptionDto, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<SubscriptionDto>>;
    apiSubscriptionIdPut(id: string, subscriptionDto?: SubscriptionDto, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/Subscription/${id}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.put(url, subscriptionDto, requestOptions);
    }
}
