/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for Email controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { RequestOptions } from "../models";

@Injectable({ providedIn: "root" })
export class EmailService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    apiEmailSendPost(ToEmail?: string, CCEmail?: string, Subject?: string, Body?: string, Attachments?: Array<Blob>, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    apiEmailSendPost(ToEmail?: string, CCEmail?: string, Subject?: string, Body?: string, Attachments?: Array<Blob>, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    apiEmailSendPost(ToEmail?: string, CCEmail?: string, Subject?: string, Body?: string, Attachments?: Array<Blob>, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    apiEmailSendPost(ToEmail?: string, CCEmail?: string, Subject?: string, Body?: string, Attachments?: Array<Blob>, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/Email/send`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Remove Content-Type for multipart (browser will set it with boundary)
        headers = headers.delete('Content-Type');

        const formData = new FormData();
        if (ToEmail !== undefined) {
            formData.append('ToEmail', String(ToEmail));
        }
        if (CCEmail !== undefined) {
            formData.append('CCEmail', String(CCEmail));
        }
        if (Subject !== undefined) {
            formData.append('Subject', String(Subject));
        }
        if (Body !== undefined) {
            formData.append('Body', String(Body));
        }
        if (Attachments !== undefined && Array.isArray(Attachments)) {
            Attachments.forEach((item) => {
                if (item !== undefined && item !== null) {
                    formData.append('Attachments', item);
                }
            });
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, formData, requestOptions);
    }
}
