/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
 * Generated by ng-openapi
 * Generated Angular service for Notification controller
 * Do not edit this file manually
 */
import {
  HttpClient,
  HttpContext,
  HttpContextToken,
  HttpEvent,
  HttpHeaders,
  HttpParams,
  HttpResponse,
} from '@angular/common/http';
import { inject, Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from '../tokens';
import { HttpParamsBuilder } from '../utils/http-params-builder';
import { NotificationDto, RequestOptions } from '../models';

@Injectable({ providedIn: 'root' })
export class NotificationService {
  private readonly httpClient: HttpClient = inject(HttpClient);
  private readonly basePath: string = inject(BASE_PATH_DEFAULT);
  private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

  private createContextWithClientId(existingContext?: HttpContext): HttpContext {
    const context = existingContext || new HttpContext();
    return context.set(this.clientContextToken, 'default');
  }

  apiNotificationPost(
    notificationDto?: NotificationDto,
    observe?: 'body',
    options?: RequestOptions<'json'>,
  ): Observable<any>;
  apiNotificationPost(
    notificationDto?: NotificationDto,
    observe?: 'response',
    options?: RequestOptions<'json'>,
  ): Observable<HttpResponse<any>>;
  apiNotificationPost(
    notificationDto?: NotificationDto,
    observe?: 'events',
    options?: RequestOptions<'json'>,
  ): Observable<HttpEvent<any>>;
  apiNotificationPost(
    notificationDto?: NotificationDto,
    observe?: 'body' | 'events' | 'response',
    options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>,
  ): Observable<any> {
    const url = `${this.basePath}/api/Notification`;

    let headers: HttpHeaders;
    if (options?.headers instanceof HttpHeaders) {
      headers = options.headers;
    } else {
      headers = new HttpHeaders(options?.headers);
    }
    // Set Content-Type for JSON requests if not already set
    if (!headers.has('Content-Type')) {
      headers = headers.set('Content-Type', 'application/json');
    }

    const requestOptions: any = {
      observe: observe as any,
      headers,
      reportProgress: options?.reportProgress,
      withCredentials: options?.withCredentials,
      context: this.createContextWithClientId(options?.context),
    };

    return this.httpClient.post(url, notificationDto, requestOptions);
  }

  apiNotificationUserIdGet(
    userId: string,
    observe?: 'body',
    options?: RequestOptions<'json'>,
  ): Observable<any>;
  apiNotificationUserIdGet(
    userId: string,
    observe?: 'response',
    options?: RequestOptions<'json'>,
  ): Observable<HttpResponse<any>>;
  apiNotificationUserIdGet(
    userId: string,
    observe?: 'events',
    options?: RequestOptions<'json'>,
  ): Observable<HttpEvent<any>>;
  apiNotificationUserIdGet(
    userId: string,
    observe?: 'body' | 'events' | 'response',
    options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>,
  ): Observable<any> {
    const url = `${this.basePath}/api/Notification/${userId}`;

    let headers: HttpHeaders;
    if (options?.headers instanceof HttpHeaders) {
      headers = options.headers;
    } else {
      headers = new HttpHeaders(options?.headers);
    }

    const requestOptions: any = {
      observe: observe as any,
      headers,
      reportProgress: options?.reportProgress,
      withCredentials: options?.withCredentials,
      context: this.createContextWithClientId(options?.context),
    };

    return this.httpClient.get(url, requestOptions);
  }

  apiNotificationMarkAsReadIdPut(
    id: string,
    observe?: 'body',
    options?: RequestOptions<'json'>,
  ): Observable<any>;
  apiNotificationMarkAsReadIdPut(
    id: string,
    observe?: 'response',
    options?: RequestOptions<'json'>,
  ): Observable<HttpResponse<any>>;
  apiNotificationMarkAsReadIdPut(
    id: string,
    observe?: 'events',
    options?: RequestOptions<'json'>,
  ): Observable<HttpEvent<any>>;
  apiNotificationMarkAsReadIdPut(
    id: string,
    observe?: 'body' | 'events' | 'response',
    options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>,
  ): Observable<any> {
    const url = `${this.basePath}/api/Notification/mark-as-read/${id}`;

    let headers: HttpHeaders;
    if (options?.headers instanceof HttpHeaders) {
      headers = options.headers;
    } else {
      headers = new HttpHeaders(options?.headers);
    }

    const requestOptions: any = {
      observe: observe as any,
      headers,
      reportProgress: options?.reportProgress,
      withCredentials: options?.withCredentials,
      context: this.createContextWithClientId(options?.context),
    };

    return this.httpClient.put(url, null, requestOptions);
  }
}
