/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for User controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { RequestOptions, UserDto, SignUpDto, LoginDto, VerifyOtpDto, CreateEmployeeUserDto } from "../models";

@Injectable({ providedIn: "root" })
export class UserService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    apiUserIdGet(id: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    apiUserIdGet(id: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    apiUserIdGet(id: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    apiUserIdGet(id: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/User/${id}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    apiUserIdPut(id: string, userDto?: UserDto, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    apiUserIdPut(id: string, userDto?: UserDto, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    apiUserIdPut(id: string, userDto?: UserDto, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    apiUserIdPut(id: string, userDto?: UserDto, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/User/${id}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.put(url, userDto, requestOptions);
    }

    apiUserIdDelete(id: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    apiUserIdDelete(id: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    apiUserIdDelete(id: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    apiUserIdDelete(id: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/User/${id}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.delete(url, requestOptions);
    }

    apiUserSignupPost(signUpDto?: SignUpDto, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    apiUserSignupPost(signUpDto?: SignUpDto, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    apiUserSignupPost(signUpDto?: SignUpDto, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    apiUserSignupPost(signUpDto?: SignUpDto, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/User/signup`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, signUpDto, requestOptions);
    }

    apiUserLoginPost(loginDto?: LoginDto, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    apiUserLoginPost(loginDto?: LoginDto, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    apiUserLoginPost(loginDto?: LoginDto, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    apiUserLoginPost(loginDto?: LoginDto, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/User/login`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, loginDto, requestOptions);
    }

    apiUserVerifyOtpPost(verifyOtpDto?: VerifyOtpDto, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    apiUserVerifyOtpPost(verifyOtpDto?: VerifyOtpDto, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    apiUserVerifyOtpPost(verifyOtpDto?: VerifyOtpDto, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    apiUserVerifyOtpPost(verifyOtpDto?: VerifyOtpDto, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/User/verify-otp`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, verifyOtpDto, requestOptions);
    }

    apiUserPublicLoginPost(loginDto?: LoginDto, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    apiUserPublicLoginPost(loginDto?: LoginDto, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    apiUserPublicLoginPost(loginDto?: LoginDto, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    apiUserPublicLoginPost(loginDto?: LoginDto, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/User/public-login`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, loginDto, requestOptions);
    }

    apiUserEmployeeUserPost(createEmployeeUserDto?: CreateEmployeeUserDto, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    apiUserEmployeeUserPost(createEmployeeUserDto?: CreateEmployeeUserDto, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    apiUserEmployeeUserPost(createEmployeeUserDto?: CreateEmployeeUserDto, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    apiUserEmployeeUserPost(createEmployeeUserDto?: CreateEmployeeUserDto, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/User/employee-user`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, createEmployeeUserDto, requestOptions);
    }

    apiUserGet(observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    apiUserGet(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    apiUserGet(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    apiUserGet(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/User`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    apiUserPost(userDto?: UserDto, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    apiUserPost(userDto?: UserDto, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    apiUserPost(userDto?: UserDto, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    apiUserPost(userDto?: UserDto, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/User`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, userDto, requestOptions);
    }
}
