/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { HttpContext, HttpHeaders } from "@angular/common/http";
export interface CreateEmployeeUserDto {
    email: string | null;
    password: string | null;
}

export interface LoginDto {
    email: string | null;
    password: string | null;
}

export interface RoleDto {
    name: string | null;
    description?: string | null;
}

export interface SignUpDto {
    email: string | null;
    password: string | null;
    phoneNumber?: string | null;
    tenantId?: string;
}

export interface UserDto {
    tenantId?: string;
    email: string | null;
    roleId?: string;
}

export interface VerifyOtpDto {
    email: string | null;
    otp: string | null;
}

/** Request Options for Angular HttpClient requests */
export interface RequestOptions<TResponseType extends 'arraybuffer' | 'blob' | 'json' | 'text'> {
    headers?: HttpHeaders;
    reportProgress?: boolean;
    responseType?: TResponseType;
    withCredentials?: boolean;
    context?: HttpContext;
}
export * from './notification-dto';
