/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for Organization controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { RequestOptions, OrganizationDTO, OrganizationPolicyDTO } from "../models";

@Injectable({ providedIn: "root" })
export class OrganizationService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    apiOrganizationSetupTenantIdGet(tenantId: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<OrganizationDTO>;
    apiOrganizationSetupTenantIdGet(tenantId: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<OrganizationDTO>>;
    apiOrganizationSetupTenantIdGet(tenantId: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<OrganizationDTO>>;
    apiOrganizationSetupTenantIdGet(tenantId: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/organization/setup/${tenantId}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    apiOrganizationSetupTenantIdPut(tenantId: string, organizationDTO?: OrganizationDTO, observe?: 'body', options?: RequestOptions<'json'>): Observable<OrganizationDTO>;
    apiOrganizationSetupTenantIdPut(tenantId: string, organizationDTO?: OrganizationDTO, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<OrganizationDTO>>;
    apiOrganizationSetupTenantIdPut(tenantId: string, organizationDTO?: OrganizationDTO, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<OrganizationDTO>>;
    apiOrganizationSetupTenantIdPut(tenantId: string, organizationDTO?: OrganizationDTO, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/organization/setup/${tenantId}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.put(url, organizationDTO, requestOptions);
    }

    apiOrganizationCountriesGet(observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    apiOrganizationCountriesGet(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    apiOrganizationCountriesGet(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    apiOrganizationCountriesGet(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/organization/countries`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    apiOrganizationPolicyTenantIdGet(tenantId: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    apiOrganizationPolicyTenantIdGet(tenantId: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    apiOrganizationPolicyTenantIdGet(tenantId: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    apiOrganizationPolicyTenantIdGet(tenantId: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/organization/policy/${tenantId}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    apiOrganizationPolicyTenantIdPut(tenantId: string, organizationPolicyDTO?: OrganizationPolicyDTO, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    apiOrganizationPolicyTenantIdPut(tenantId: string, organizationPolicyDTO?: OrganizationPolicyDTO, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    apiOrganizationPolicyTenantIdPut(tenantId: string, organizationPolicyDTO?: OrganizationPolicyDTO, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    apiOrganizationPolicyTenantIdPut(tenantId: string, organizationPolicyDTO?: OrganizationPolicyDTO, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/organization/policy/${tenantId}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.put(url, organizationPolicyDTO, requestOptions);
    }

    apiOrganizationTimezonesGet(observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    apiOrganizationTimezonesGet(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    apiOrganizationTimezonesGet(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    apiOrganizationTimezonesGet(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/organization/timezones`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    organizationGetAll(observe?: 'body', options?: RequestOptions<'json'>): Observable<Array<OrganizationDTO>>;
    organizationGetAll(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Array<OrganizationDTO>>>;
    organizationGetAll(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Array<OrganizationDTO>>>;
    organizationGetAll(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/organization`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    organizationCreate(organizationDTO?: OrganizationDTO, observe?: 'body', options?: RequestOptions<'json'>): Observable<OrganizationDTO>;
    organizationCreate(organizationDTO?: OrganizationDTO, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<OrganizationDTO>>;
    organizationCreate(organizationDTO?: OrganizationDTO, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<OrganizationDTO>>;
    organizationCreate(organizationDTO?: OrganizationDTO, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/organization`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, organizationDTO, requestOptions);
    }

    organizationGetById(id: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<OrganizationDTO>;
    organizationGetById(id: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<OrganizationDTO>>;
    organizationGetById(id: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<OrganizationDTO>>;
    organizationGetById(id: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/organization/${id}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    organizationUpdate(id: string, organizationDTO?: OrganizationDTO, observe?: 'body', options?: RequestOptions<'json'>): Observable<OrganizationDTO>;
    organizationUpdate(id: string, organizationDTO?: OrganizationDTO, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<OrganizationDTO>>;
    organizationUpdate(id: string, organizationDTO?: OrganizationDTO, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<OrganizationDTO>>;
    organizationUpdate(id: string, organizationDTO?: OrganizationDTO, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/organization/${id}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.put(url, organizationDTO, requestOptions);
    }

    apiOrganizationIdDelete(id: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    apiOrganizationIdDelete(id: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    apiOrganizationIdDelete(id: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    apiOrganizationIdDelete(id: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/organization/${id}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.delete(url, requestOptions);
    }
}
