/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { HttpContext, HttpHeaders } from "@angular/common/http";
export enum BillingCycle {
    _1 = 1,
    _2 = 2,
    _3 = 3
}

export interface PaymentDto {
    id?: string;
    invoiceId?: string;
    amount?: number;
    currency?: string | null;
    paymentMethod?: string | null;
    transactionId?: string | null;
    status?: PaymentStatus;
    paidAt?: Date;
    gatewayResponse?: string | null;
}

export enum PaymentStatus {
    _1 = 1,
    _2 = 2,
    _3 = 3,
    _4 = 4
}

export interface PlanDto {
    id?: string;
    name?: string | null;
    code?: string | null;
    description?: string | null;
    monthlyPrice?: number;
    yearlyPrice?: number;
    trialDays?: number;
    isActive?: boolean;
    createdAt?: Date;
}

export interface SubscriptionDto {
    id?: string;
    tenantId?: string;
    planId?: string;
    startDate?: Date;
    endDate?: Date;
    billingCycle?: BillingCycle;
    status?: SubscriptionStatus;
    autoRenew?: boolean;
    isTrial?: boolean;
    cancelledAt?: Date | null;
    createdAt?: Date;
}

export enum SubscriptionStatus {
    _1 = 1,
    _2 = 2,
    _3 = 3,
    _4 = 4,
    _5 = 5
}

/** Request Options for Angular HttpClient requests */
export interface RequestOptions<TResponseType extends 'arraybuffer' | 'blob' | 'json' | 'text'> {
    headers?: HttpHeaders;
    reportProgress?: boolean;
    responseType?: TResponseType;
    withCredentials?: boolean;
    context?: HttpContext;
}
