/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { HttpContext, HttpHeaders } from "@angular/common/http";
export enum CompanySize {
    Small = "Small",
    Medium = "Medium",
    Large = "Large"
}

export enum DateFormatType {
    DDMMYYYY = "DD_MM_YYYY",
    MMDDYYYY = "MM_DD_YYYY",
    YYYYMMDD = "YYYY_MM_DD",
    DDMMMYYYY = "DD_MMM_YYYY",
    DDMMMYY = "DD_MMM_YY",
    MMMDDYYYY = "MMM_DD_YYYY"
}

export enum NameFormatType {
    FIRSTLAST = "FIRST_LAST",
    LASTFIRST = "LAST_FIRST",
    FIRSTMIDDLELAST = "FIRST_MIDDLE_LAST",
    FIRST = "FIRST",
    LAST = "LAST"
}

export interface OrganizationDTO {
    id?: string;
    name: string;
    subdomain: string;
    website: string;
    organizationType: string;
    contactPerson: string;
    contactNumber: string;
    contactEmail: string;
    address: string;
    city: string;
    state: string;
    country: string;
    zipCode: string;
    logo?: string | null;
    theme?: ThemeTypes;
    status: TenantStatus;
}

export interface OrganizationPolicyDTO {
    notifications?: boolean;
    chat?: boolean;
    aiAssistant?: boolean;
    birthdayVisibility?: boolean;
    workAnniversaryVisibility?: boolean;
    mobileNumberVisibility?: boolean;
    mobileSearchAccess?: boolean;
    updatePermission?: string | null;
    systemCoverImage?: boolean;
    customCoverUpload?: boolean;
    recordRetentionMonths?: number;
    profileUpdateApproval?: boolean;
    countryId?: string;
    timeZoneId?: string;
    nameFormat?: NameFormatType;
    dateFormat?: DateFormatType;
    timeFormat?: TimeFormatType;
}

export interface TenantDto {
    name: string | null;
    domain?: string | null;
    subdomain: string | null;
    industry?: string | null;
    companySize?: CompanySize;
    country: string | null;
    timeZone: string | null;
    currency: string | null;
    address?: string | null;
    city?: string | null;
    state?: string | null;
    postalCode?: string | null;
    contactEmail: string | null;
    contactPhone?: string | null;
    status?: TenantStatus;
    subscriptionId?: string;
    trialStartDate?: Date | null;
    trialEndDate?: Date | null;
    isTrial?: boolean;
    createdAt?: Date;
    createdBy?: string;
    updatedAt?: Date | null;
}

export enum TenantStatus {
    Active = "Active",
    Suspended = "Suspended",
    Trial = "Trial"
}

export enum ThemeTypes {
    OceanBlue = "OceanBlue",
    Emerald = "Emerald",
    SunsetOrange = "SunsetOrange",
    RoyalPurple = "RoyalPurple",
    RosePink = "RosePink",
    MidnightDark = "MidnightDark",
    Violet = "Violet"
}

export enum TimeFormatType {
    TWELVEHOUR = "TWELVE_HOUR",
    TWENTYFOURHOUR = "TWENTY_FOUR_HOUR"
}

/** Request Options for Angular HttpClient requests */
export interface RequestOptions<TResponseType extends 'arraybuffer' | 'blob' | 'json' | 'text'> {
    headers?: HttpHeaders;
    reportProgress?: boolean;
    responseType?: TResponseType;
    withCredentials?: boolean;
    context?: HttpContext;
}
